### ISSUE TITLE
Smart Controller and Windows SDK

### ISSUE THREAD

**Issue by SeanMcEn** [dji-sdk/Windows-SDK#44]
Do I understand correctly from dji-devs answer in this issue https://github.com/dji-sdk/Windows-SDK/issues/32 that the Windows SDK does not work with the Smart Controller?

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/31850'>Zendesk ticket #31850</a>:<br><br>Hi Sean,

Thank you for contacting DJI Developer Support with your question. Yes, your understanding is correct the WSDK can not be run on the Smart Controller. The reason is because Smart Controllers run Android OS.

Let us know if you have further questions!

Warm Regards,

Lisa Fedane
DJI Developer Support

**Comment by SeanMcEn** [comment]
Thanks Lisa, 
To clarify, I am clear that a WSDK application will not run ON the Smart Controller-being different operating systems. My question is does the WSDK work WITH the Smart Controller.
Will the  WSDK examples provided work if I buy the Smart Controller pack- ie receiving video to a laptop application, sending mission waypoints, getting drone data etc. 
Apologies if this is what you have already answered- I just want to be clear.
Sean

**Comment by dji-dev** [comment]
Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/31850'>Zendesk ticket #31850</a>:<br><br>Hi Sean. I am sorry to tell you if you use the smart controller the WSDK can not control the drone. If you want to use windows SDK please choose the remote control as the picture below.
 ![](https://djisdksupport.zendesk.com/attachments/token/bWqCXSPxs3JMBMUa2qAJWG3c2/?name=inline1080378922.png)​<br><a href='https://djisdksupport.zendesk.com/attachments/token/bWqCXSPxs3JMBMUa2qAJWG3c2' target='zd_attach'>inline1080378922.png</a>

**Comment by SeanMcEn** [comment]
Thankyou for clarifying this.
