### ISSUE TITLE
List of supported drones

### ISSUE THREAD

**Issue by iN1k1** [dji-sdk/Windows-SDK#9]
Any chance of of having additional DJI drones supported (e.g. M series or P4 pro)?

Thanks
Niki

**Comment by TheRedMudder** [comment]
@iN1k1  I surely hope so, but fear they're creating an incentive for users to upgrade by not supporting the P4 Pro or M series. Now developers can utilize computer hardware to create more powerful drone apps, ex: combing CNN with the live video feed to identify trees, cars, and humans. Once these apps are released users will want to upgrade to take advantage of them because other than propulsion changes and Occusync WiFi support, there is no reason to upgrade to a P4 Pro V2 from the Pro. Now they added Windows drone app to the list of reasons to upgrade.

**Comment by iN1k1** [comment]
Thx @TheRedMudder.. It seems that "old" products are not of interest.. :(
